name: Migration

on:
  pull_request:
    branches: 
      - master
      
env:
  sourceSubscriptionId: Your value
  sourceResourceGroupName: Your value
  sourceServiceName: Your value
  sourceAzureTenantId: Your value
  sourceServicePrincipal: Your value
  sourceServicePrincipalSecret:  ${{ secrets.SourcePrincipalSecret }}
  destSubscriptionId: Your value
  destResourceGroupName: Your value
  destServiceName: Your value
  destServicePrincipal: Your value
  destServicePrincipalSecret: ${{ secrets.DestPrincipalSecret }}

jobs:
  migrate:
    name: Migration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Migrate
        run:
          node ./migrate --sourceSubscriptionId "${{ env.sourceSubscriptionId }} --sourceResourceGroupName  "${{ env.sourceResourceGroupName }} --sourceServiceName "${{ env.sourceServiceName }} --destServiceName "${{ env.destServiceName }} --destSubscriptionId "${{ env.destSubscriptionId }} --destResourceGroupName "${{ env.destResourceGroupName }} --sourceTenantId "${{ env.sourceAzureTenantId }} --sourceServicePrincipal "${{ env.sourceServicePrincipal }} --sourceSecret "${{ env.sourceServicePrincipalSecret }}  --destTenantId "${{ env.sourceAzureTenantId }} --destServicePrincipal "${{ env.destServicePrincipal }} --destSecret "${{ env.destServicePrincipalSecret }}
